Blood_project/Blood_app/urls.py
from django.conf.urls import url
from Blood_app import views

app_name = 'Blood_app'

urlpatterns =[
    url(r'^$',views.index,name = 'index'),
    url(r'^signup/$',views.Sign_up,name='signup')
    ]

Blood_project/Blood_project/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from Blood_app import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^Blood_app/',include("Blood_app.urls")),
    path('admin/', admin.site.urls),
]

Blood_project/Blood_app/models.py
from django.db import models

# Create your models here.
# class Dhirajlal_gandhi_college_of_technology(models.Model):

class Add_donors(models.Model):
    student_name = models.CharField(max_length = 264,unique=True)
    batch = models.CharField(max_length = 10)
    address = models.CharField(max_length=264)
    blood_group= models.CharField(max_length=5)
    mobile_number = models.CharField(max_length=10,unique=True)
    date_of_birth =models.DateField()

    def __str__(self):
        return self.batch

Blood_project/Blood_app/forms.py
from django import forms
from Blood_app.models import Add_donors

class Add_donors_form(forms.ModelForm):
    class Meta():
        model = Add_donors
        fields = '__all__'

Blood_project/Blood_app/views.py
from django.shortcuts import render
from Blood_app.forms import Add_donors_form
# Create your views here.
def index(request):
    return render(request,"Blood_app/index.html")

def Sign_up(request):
    form = Add_donors_form()

    if request.method =='POST':
        form = Add_donors_form(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("It is not valid..!! please verify")

    return render(request,"Blood_app/signup.html",{'form':form})

Blood_project/templates/Blood_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title></title>
    <!-- <style>
    #userlogin,#adminlogin : hover{
      background-color: black;
    }
    </style> -->
  </head>
  <body>
      <h1 style="color: white;text-align: center;background-color: black;margin:0px 0px 0px 0px; padding:0px 0px 0px 0px;">Uyirottam</h1>
    <nav class="navbar navbar-expand-lg" style="background-color: black; margin: 0px 0px 5px 0px;" >
      <div class="container">
        <a class="navbar-brand"style="color:white;" href="{% url 'Blood_app:index' %}">
         <img src="{% static "images/Blood donors logo.JPEG" %}" width="30" height="30" class="d-inline-block align-top" alt="">
         Uyirottam
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a style="color:white;"class="nav-link" href="{% url 'Blood_app:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a style="color:white;"class="nav-link" href="#">About</a>
            </li>
          </ul>
          <ul class="navbar-nav mt-2 mt-lg-0">
            <li class="nav-item dropdown">
              <a style="color:white;"class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Login!
              </a>
              <div class="dropdown-menu" style="background-color:black;"aria-labelledby="navbarDropdown">
                <a style="color: white;background-color: black;"class="dropdown-item" href="#">User Login</a>
                <a style="color: white;background-color: black;"class="dropdown-item" href="{% url 'Blood_app:signup' %}">User Signup</a>
                <a style="color: white;background-color: black;"class="dropdown-item" href="{% url 'admin:index' %}">Admin Login</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

Blood_project/templates/Blood_app/index.html
{% extends "Blood_app/base.html" %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/indexstyle.css" %}">
{% block body_block %}
    <table id="mt">
      <tr id='h'>
        <td style="text-align: center;"><strong>Donors Eligibilities..</strong></td>
        <td style="text-align: center;"><strong>Donors Non-Eligibilities</strong></td>
      </tr>
      <tr>
        <td><ul id="p1">
          <li>Any donor, who is healthy, fit and not suffering from any transmittable diseases can donate blood.</li>
          <li>Donor must be 18 -60 years age and having a minimum weight of 50Kg can donate blood.</li>
          <li>Donor’s Hemoglobin level is 12.5% minimum.</li>
          <li>A donor can again donate blood after 3 months of your last donation of blood.</li>
          <li>Pulse rate must be between 50 to 100mm without any irregularities.</li>
          <li>BP Diastolic 50 to 100 mm Hg and Systolic 100 to 180 mm Hg.</li>
          <li>  Body temperature should be normal and oral temperature should not exceed 37.5 degree Celsius.</li>
        </ul></td>
        <td><ul id="p2">
          <li>Donors should not suffer from Cardiac arrest, hypertension, kidney alignments,epilepsy or diabetics.</li>
          <li>  Ladies with a bad miscarriage should avoid donating blood for the next 6 months.</li>
          <li>If donor already donated blood or have been treated for malaria within the last three months.</li>
          <li>If donor undergone any immunization within the past one month.</li>
          <li>If donor consumed alcohol within the last 24 hours.</li>
          <li>If you are HIV+.</li>
          <li>If donor had a dental work for next 24 hours and wait for one month if donor had a major dental procedure.</li>
          </ul></td>
      </tr>
    </table>
    <img id="infoimg" src="{% static 'images/BT.jpg' %}" alt="" width="200" height="180">
    <!-- <table id="t1">
      <tr id="loginheading">
        <td>Admin Login</td>
        <td>User Login</td> -->
        <!-- <td>User signup</td> -->
      <!-- </tr>
      <tr>
        <td id="cell1">
          <form action="http://evanerichards.com/wp-content/uploads/2013/12/Thanks-580x250.gif" method="get">
            <table id="in1">
              <tr>
                <td>User ID:</td>
                <td><input type="text" name="User"placeholder="MuraliKrishna"required></td>
              </tr>
              <tr>
                <td>Password:</td>
                <td><input id="pass1"type="password" name="adminpass" placeholder="1230456"required></td>
              </tr>
              <tr id="loginrow1">
                <td colspan="2"><input type="submit"name="Submitadmin" value="Login"></td>
              </tr>
            </table>
          </form>
        </td>
        <td id="cell2">
          <form action="http://evanerichards.com/wp-content/uploads/2013/12/Thanks-580x250.gif" method="get">
            <table id="in2">
              <tr>
                <td>User ID:</td>
                <td><input id="r12" type="text" name="Usersignup"placeholder="User name"required></td>
              </tr>
              <tr>
                <td>Password:</td>
                <td><input id="pass2"type="password" name="userpass" placeholder="1230456"required></td>
              </tr>
              <tr>
                <td id="linkfsu"><a href="E:\002 Django-Python-Full-Stack-Web-Developer-Material\Django-Python-Full-Stack-Web-Devloper-master\CSS_Level_Two\Signupform.html">Be a hero!<br>Sign up..!</a></td>
                <td id="loginrow2"><input type="Submit" name="Usersubmit" value="Login"></form></td>
              </tr>
            </table>
          </form>
        </td>
      </tr>
    </table> -->
{% endblock %}

Blood_project/templates/Blood_app/signup.html
{% extends 'Blood_app/base.html' %}
{% block body_block %}
<h3> Please sign up..!!</h3>
{{ form.as_p }}
{% csrf_token %}
<input type="submit" class="btn btn-primary" value="submit">
{% endblock %}